on: [push]
  
jobs:      
  job1:
    runs-on: ubuntu-latest
    name: createCustomImage
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - shell: bash
      run: mkdir -p homework
    
    - shell: bash
      run: |
          echo "echo Installing World..." > installScripts/install-world.sh |
          echo "echo Installing Universe..." > installScripts/install-universe.sh
    
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: aib action
      id: aib
      uses: ./
      with:
        location: 'eastus2'
        resourceGroupName: 'raiaib-rg'
        sourceOSType: 'linux'
        sourceImageType: 'marketplace'
        sourceImage: Canonical:UbuntuServer:18.04-LTS:latest
        customizerSource: '/home/runner/work/imageBuilder/installScripts'
        distributorType: 'sharedgalleryimage'
        distResourceId: '/subscriptions/439f6f90-fc63-4d40-8a25-33cdf46c730c/resourceGroups/rogoyal/providers/Microsoft.Compute/galleries/rogoyalsig/images/rogoyalimgdefn'
        distLocation: 'eastus2'

    - name: print aib output
      run: echo output from aib ${{ steps.aib.outputs.imagebuilderRunStatus }} ${{ steps.aib.outputs.runOutputName }} ${{ steps.aib.outputs.customImageURI }}
